EWPP-372: Fix drupal type file extensions to be checked.
ec-europa/oe-code-review pull request #129
Opened 2021-02-01 14:58 UTC by nagyad

2021-02-02 10:13 UTC, sergepavle approved these changes, later dismissed

2021-02-02 12:18 UTC, 22Alexandra submitted a review, later dismissed

2021-02-02 14:23 UTC, 22Alexandra submitted a review, later dismissed

2021-02-02 14:23 UTC, sergepavle approved these changes, later dismissed

2021-02-03 14:39 UTC, ademarco requested changes

2021-02-03 14:39 UTC, ademarco commented on composer.json
> +    "phpro/grumphp": "0.15.2",
Let's actually update to ~0.17.0.

2021-02-11 13:29 UTC, sergepavle approved these changes

2021-04-21 12:36 UTC, ademarco approved these changes

2021-04-21 12:38 UTC, merged