OEL-3256: Upgrade GrumPHP to v2 (WIP)
ec-europa/oe-code-review pull request #159
Opened 2024-08-14 12:27 UTC by AaronGilMartinez

2024-08-22 16:31 UTC, brummbar approved these changes, later dismissed

2024-08-23 10:21 UTC, drishu requested changes

2024-08-23 10:21 UTC, drishu commented on README.md
> +GrumPHP tasks will be ran at every commit, if you with to run them without performing a commit use the following command:
```suggestion
GrumPHP tasks will be run at every commit, if you wish to run them without performing a commit use the following command:
```

2024-08-23 10:51 UTC, AaronGilMartinez commented on README.md
> +GrumPHP tasks will be ran at every commit, if you with to run them without performing a commit use the following command:
Fixed, thanks

2024-08-23 11:11 UTC, drishu approved these changes

2024-08-23 14:00 UTC, brummbar approved these changes

2024-08-23 14:03 UTC, merged